<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-91E2CJV" failures="1" tests="9" name="AuthService" time="8.127" errors="0" timestamp="2022-12-08T10:16:59 EET">
  <testcase classname="net.absoft.AuthenticationServiceTest" name="failingTest" time="2.001">
    <skipped/>
  </testcase> <!-- failingTest -->
  <testcase classname="net.absoft.AuthenticationServiceTest" name="failingTest" time="2.0">
    <skipped/>
  </testcase> <!-- failingTest -->
  <testcase classname="net.absoft.AuthenticationServiceTest" name="failingTest" time="2.001">
    <skipped/>
  </testcase> <!-- failingTest -->
  <testcase classname="net.absoft.AuthenticationServiceTest" name="failingTest" time="2.0">
    <failure type="java.lang.AssertionError" message="Failing test!">
      <![CDATA[java.lang.AssertionError: Failing test!
at net.absoft.AuthenticationServiceTest.failingTest(AuthenticationServiceTest.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- failingTest -->
  <testcase classname="net.absoft.AuthenticationServiceTest" name="testInvalidAuthentication" time="0.0"/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="testInvalidAuthentication" time="0.016"/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="testInvalidAuthentication" time="0.0"/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="testInvalidAuthentication" time="0.0"/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="testSuccessfulAuthentication" time="0.0"/>
</testsuite> <!-- AuthService -->
